### PR TITLE
Add process json data array method

### PR DESCRIPTION
**Pull request by joshwoods**

### CODE REVIEW

**Comment by UpBra** [comment]
This is a pretty common practice in swift. I can't find it in Apple's documentation but it's basically generic method overloading. Apple uses this in a lot of its Init methods:

> Int(_ value: Float)
> Int(_ value: Int16)

What's your thought process, @joshwoods,  behind why we need to change the method signature to accommodate for the two different parameter types?

**Comment by joshwoods** [comment]
True, but at the same time on our end with something that's so important to get right, the naming is pretty important. Maybe it can be chalked up to inexperience using Horatio itself but, either way, being a little bit more verbose to cut down on any potential confusion as to why our data isn't being parsed can go a long way.

**Comment by joshwoods** [comment]
@UpBra @ktatroe actually taking this a little bit further, if we wanted, we could really update both methods:

    func process(_ jsonData: JSONObject, forRequest request: ServiceRequest, completionBlock: @escaping (_ errors: [NSError]?) -> Void)
    func process(_ jsonDataArray: [JSONObject], forRequest request: ServiceRequest, completionBlock: @escaping (_ errors: [NSError]?) -> Void)

What would you think about that?

**Comment by UpBra** [comment]
I'm actually in favor of the overloading implementation. It's a standard swift practice and seems cleaner. The only other implementations i can think of that seem cleaner and easier to me would be using the variadic parameter JSONObject... (then everyone is always dealing with an array) or providing a default implementation of the value: JSONObject implementation that simply calls the value: [JSONObject] method

**Comment by joshwoods** [comment]
`//
//  Copyright © 2016 Kevin Tatroe. All rights reserved.
//  See LICENSE.txt for this sample’s licensing information

import Foundation


/**
 Processes JSON data in some way — transforming, storing, or otherwise manipulating the data.
 */
public protocol JSONProcessor {
    func process(jsonData: [JSONObject], forRequest request: ServiceRequest, completionBlock: @escaping (_ errors: [NSError]?) -> Void)
    @available(*, deprecated, message: "Please use process:jsonData:forRequest instead.")
    func processJSONData(_ request: ServiceRequest, jsonData: JSONObject, completionBlock: @escaping (_ errors: [NSError]?) -> Void)
    @available(*, deprecated, message: "Please use process:jsonData:forRequest instead.")
    func processJSONData(_ request: ServiceRequest, jsonData: [JSONObject], completionBlock: @escaping (_ errors: [NSError]?) -> Void)
}


extension JSONProcessor {
    func processJSONData(_ request: ServiceRequest, jsonData: JSONObject, completionBlock: @escaping (_ errors: [NSError]?) -> Void) {
        print("🚫This processJSONData method has been deprecated. Please use process:jsonData:forRequest instead.🚫")
        process(jsonData: [jsonData], forRequest: request) { (_) in
            completionBlock(nil)
        }
    }
    
    func processJSONData(_ request: ServiceRequest, jsonData: [JSONObject], completionBlock: @escaping (_ errors: [NSError]?) -> Void) {
        print("🚫This processJSONData method has been deprecated. Please use process:jsonData:forRequest instead.🚫")
        process(jsonData: jsonData, forRequest: request) { (_) in
            completionBlock(nil)
        }
    }
    
    func process(jsonData: [JSONObject], forRequest request: ServiceRequest, completionBlock: @escaping (_ errors: [NSError]?) -> Void) {
        completionBlock(nil)
    }
}


/**
 Processes JSON data from a response object and returns an error or a terminal processed case.
 A JSON processor takes a specialized processor for parsing JSON (typically, parsing the JSON
 into objects and storing those in a local store).
 */
open class JSONServiceResponseProcessor: ServiceResponseProcessor {
    // MARK: - Properties

    let jsonProcessor: JSONProcessor


    // MARK: - Initialization


    public init(jsonProcessor: JSONProcessor) {
        self.jsonProcessor = jsonProcessor
    }


    // MARK: - Protocols

    // MARK: <ServiceResponseProcessor>

    open func process(_ request: ServiceRequest, input: ServiceResponseProcessorParam, completionBlock: @escaping (ServiceResponseProcessorParam) -> Void) {
        var jsonData: Any? = nil
        
        do {
            switch input {
            case .stream(let inputStream):
                jsonData = try JSONSerialization.jsonObject(with: inputStream, options: .allowFragments)
                
            case .data(_, let inputData):
                jsonData = try JSONSerialization.jsonObject(with: inputData, options: .allowFragments)
                
            default:
                completionBlock(input)
            }
        } catch let jsonError as NSError {
            print("Error parsing response from \(String(describing: request.url)): \(jsonError)")
            completionBlock(.error(jsonError))
        }

        if let jsonObject = jsonData as? JSONObject {
            process(jsonData: [jsonObject], forRequest: request, completionBlock: completionBlock)
        } else if let jsonArray = jsonData as? [JSONObject] {
            process(jsonData: jsonArray, forRequest: request, completionBlock: completionBlock)
        } else {
            completionBlock(.processed(false))
        }
    }
    
    
    // MARK: - Private


    fileprivate func process(jsonData: [JSONObject], forRequest request: ServiceRequest, completionBlock: @escaping (ServiceResponseProcessorParam) -> Void) {
        jsonProcessor.process(jsonData: jsonData, forRequest: request) { (errors: [NSError]?) in
            if let error = errors?.first {
                completionBlock(.error(error))
                return
            }
            
            completionBlock(.processed(true))

        }
    }
}
`

**Comment by joshwoods** [comment]
What about just condensing them both down into a singular method?

`    func process(jsonData: [JSONObject], forRequest request: ServiceRequest, completionBlock: @escaping (_ errors: [NSError]?) -> Void)
`

That would make our if-block in the ServiceResponseProcessor look like this:

`        if let jsonObject = jsonData as? JSONObject {
            process(jsonData: [jsonObject], forRequest: request, completionBlock: completionBlock)
        } else if let jsonArray = jsonData as? [JSONObject] {
            process(jsonData: jsonArray, forRequest: request, completionBlock: completionBlock)
        } else {
            completionBlock(.processed(false))
        }
`
Devs would need to be aware that their data would always be considered an array, but at the same time this would alleviate any confusion that could come from having two separate methods doing essentially the same exact thing.

**Comment by ktatroe** [comment]
I feel that this is app-side logic in the current API.

**Pull request closed without merging**
